include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

image: ubuntu:bionic

variables: &variables
  JULIA_CUDA_VERBOSE: 'true'
  NVIDIA_VISIBLE_DEVICES: 'all'
  NVIDIA_DRIVER_CAPABILITIES: 'compute,utility'
  BINARYBUILDER_STORAGE_DIR: 'downloads'


# Julia versions

julia:1.0:
  extends:
    - .julia:1.0
    - .test
  tags:
    - nvidia

julia:1.1:
  extends:
    - .julia:1.1
    - .test
  tags:
    - nvidia

# the "primary" target, where we require a new GPU to make sure all tests are run
julia:1.2:
  extends:
    - .julia:1.2
    - .test
  tags:
    - nvidia
    - sm_75

julia:1.3:
  extends:
    - .julia:1.3
    - .test
  tags:
    - nvidia

julia:nightly:
  extends:
    - .julia:nightly
    - .test
  tags:
    - nvidia
  allow_failure: true


# CUDA versions

# NOTE: we support those CUDA versions for which the latest cuDNN is available
#       https://developer.nvidia.com/rdp/cudnn-archive

cuda:10.1:
  extends:
    - .julia:1.2
    - .test
  variables:
    <<: *variables
    JULIA_CUDA_VERSION: '10.1'
  tags:
    - nvidia

cuda:10.0:
  extends:
    - .julia:1.2
    - .test
  variables:
    <<: *variables
    JULIA_CUDA_VERSION: '10.0'
  tags:
    - nvidia

cuda:9.2:
  extends:
    - .julia:1.2
    - .test
  variables:
    <<: *variables
    JULIA_CUDA_VERSION: '9.2'
  tags:
    - nvidia

cuda:9.0:
  extends:
    - .julia:1.2
    - .test
  variables:
    <<: *variables
    JULIA_CUDA_VERSION: '9.0'
  tags:
    - nvidia

cuda:local:
  extends:
    - .julia:1.2
    - .test
  image: nvidia/cuda:10.1-devel-ubuntu18.04
  variables:
    <<: *variables
    JULIA_CUDA_USE_BINARYBUILDER: 'false'
  tags:
    - nvidia

cuda:none:
  extends:
    - .julia:1.2
    - .test
  variables:
    JULIA_CUDA_VERBOSE: 'true'
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --project -e 'using Pkg;
                          Pkg.instantiate();
                          Pkg.build();
                          Pkg.API.precompile()'
    - julia --project -e 'using CUDAnative;
                          CUDAnative.load_runtime(v"7.0")'


# reverse tests

# NOTE: reverse testing is tricky because of Manifests. we instantiate both, give priority
#       to this package's Manifest, and manually run tests outside of the test environment.
#       that means we have to manually install CuArrays' test dependencies though.

cuarrays:
  extends:
    - .julia:1.2
    - .test
  tags:
    - nvidia
  script:
    - export CUARRAYS="$HOME/.julia/dev/CuArrays"
    - julia -e 'using Pkg;
                Pkg.develop("CuArrays");'
    - julia --project -e 'using Pkg;
                          Pkg.instantiate();
                          Pkg.build();'
    - julia --project=$CUARRAYS -e 'using Pkg;
                                    Pkg.instantiate();
                                    Pkg.build();
                                    Pkg.add(["FFTW", "ForwardDiff", "FillArrays"]);'
    - JULIA_LOAD_PATH=".:$CUARRAYS::" julia $CUARRAYS/test/runtests.jl
  allow_failure: true


# other tasks

coverage:
  extends:
    - .julia:1.2
    - .coverage

documentation:
  extends:
    - .julia:1.2
    - .documentation
  tags:
    - nvidia

pages:
  stage: deploy
  script:
    - mv docs/build public
  artifacts:
    paths:
    - public
  only:
    - master
